const mongoose = require("mongoose");
const Recipe = require("./models/Recipe.js");
const connectToDB = require("./config/db.js");
require("dotenv").config();

const mockRecipes = [
  {
    name: "Mediterranean Quinoa Bowl",
    image:
      "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Mediterranean",
    dietaryTags: ["Vegetarian", "Gluten-Free", "High-Protein"],
    nutrition: {
      calories: 450,
      protein: 18,
      carbs: 65,
      fat: 14,
      fiber: 8,
      sugar: 6,
    },
    ingredients: [
      "1 cup quinoa",
      "2 cups vegetable broth",
      "1 cucumber, diced",
      "1 cup cherry tomatoes",
      "1/2 red onion, sliced",
      "1/4 cup kalamata olives",
      "1/4 cup feta cheese",
      "2 tbsp olive oil",
      "1 lemon, juiced",
      "Fresh herbs (parsley, dill)",
    ],
    instructions: [
      "Cook quinoa in vegetable broth according to package directions",
      "Let quinoa cool completely",
      "Dice cucumber and halve cherry tomatoes",
      "Slice red onion thinly",
      "Combine all vegetables with quinoa",
      "Whisk olive oil and lemon juice",
      "Toss with dressing and top with feta and herbs",
    ],
  },
  {
    name: "Grilled Salmon with Asparagus",
    image:
      "https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&w=400",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "Medium",
    cuisine: "American",
    dietaryTags: ["High-Protein", "Keto-Friendly", "Low-Carb"],
    nutrition: {
      calories: 380,
      protein: 35,
      carbs: 8,
      fat: 22,
      fiber: 4,
      sugar: 4,
    },
    ingredients: [
      "2 salmon fillets (6 oz each)",
      "1 lb asparagus, trimmed",
      "2 tbsp olive oil",
      "1 lemon, sliced",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
      "Fresh dill for garnish",
    ],
    instructions: [
      "Preheat grill to medium-high heat",
      "Brush salmon and asparagus with olive oil",
      "Season with salt, pepper, and garlic",
      "Grill salmon 4-5 minutes per side",
      "Grill asparagus 5-7 minutes until tender",
      "Serve with lemon slices and fresh dill",
    ],
  },
  {
    name: "Overnight Oats with Berries",
    image:
      "https://images.pexels.com/photos/704571/pexels-photo-704571.jpeg?auto=compress&cs=tinysrgb&w=400",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    cuisine: "American",
    dietaryTags: ["Vegetarian", "High-Fiber", "Make-Ahead"],
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 58,
      fat: 8,
      fiber: 10,
      sugar: 18,
    },
    ingredients: [
      "1/2 cup rolled oats",
      "1/2 cup milk of choice",
      "1 tbsp chia seeds",
      "1 tbsp maple syrup",
      "1/2 cup mixed berries",
      "1 tbsp almond butter",
      "1/4 tsp vanilla extract",
    ],
    instructions: [
      "Combine oats, milk, chia seeds, and maple syrup in a jar",
      "Add vanilla extract and mix well",
      "Top with berries and almond butter",
      "Refrigerate overnight",
      "Enjoy cold or heat briefly before eating",
    ],
  },
  {
    name: "Chicken Stir Fry",
    image:
      "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=400",
    prepTime: 15,
    cookTime: 12,
    servings: 3,
    difficulty: "Medium",
    cuisine: "Asian",
    dietaryTags: ["High-Protein", "Low-Carb", "Gluten-Free"],
    nutrition: {
      calories: 285,
      protein: 28,
      carbs: 12,
      fat: 15,
      fiber: 3,
      sugar: 8,
    },
    ingredients: [
      "1 lb chicken breast, sliced",
      "2 cups mixed vegetables",
      "2 tbsp coconut oil",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "1 tsp red pepper flakes",
    ],
    instructions: [
      "Heat coconut oil in a large wok or skillet",
      "Add chicken and cook until golden brown",
      "Add garlic and ginger, stir for 30 seconds",
      "Add vegetables and stir-fry for 3-4 minutes",
      "Mix in soy sauce, sesame oil, and red pepper flakes",
      "Cook for another 2 minutes until vegetables are tender-crisp",
      "Serve immediately over rice or noodles",
    ],
  },
  {
    name: "Avocado Toast with Eggs",
    image:
      "https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&w=400",
    prepTime: 8,
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    cuisine: "American",
    dietaryTags: ["Vegetarian", "High-Protein", "Healthy-Fats"],
    nutrition: {
      calories: 395,
      protein: 18,
      carbs: 28,
      fat: 26,
      fiber: 12,
      sugar: 3,
    },
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tbsp olive oil",
      "Salt and pepper to taste",
      "Red pepper flakes",
      "Lemon juice",
      "Fresh herbs for garnish",
    ],
    instructions: [
      "Toast bread slices until golden brown",
      "Mash avocado with lemon juice, salt, and pepper",
      "Heat olive oil in a pan and fry eggs to desired doneness",
      "Spread mashed avocado on toast",
      "Top with fried eggs",
      "Season with red pepper flakes and fresh herbs",
      "Serve immediately",
    ],
  },
  {
    name: "Paneer Butter Masala",
    image:
      "https://vegecravings.com/wp-content/uploads/2017/04/paneer-butter-masala-recipe-step-by-step-instructions.jpg",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietaryTags: ["Vegetarian", "High-Protein", "Gluten-Free"],
    nutrition: {
      calories: 450,
      protein: 18,
      carbs: 20,
      fat: 35,
      fiber: 3,
      sugar: 6,
    },
    ingredients: [
      "250g paneer, cubed",
      "2 tbsp butter",
      "1 cup tomato puree",
      "1/2 cup cream",
      "1 onion, finely chopped",
      "1 tsp garam masala",
      "1 tsp red chili powder",
      "Salt to taste",
      "2 cloves garlic, minced",
      "1-inch ginger, grated",
    ],
    instructions: [
      "Heat butter in a pan, sauté onion, garlic, and ginger",
      "Add tomato puree, cook until oil separates",
      "Stir in cream, spices, and salt",
      "Add paneer cubes and simmer 10 minutes",
      "Garnish with cream and coriander",
      "Serve with naan or rice",
    ],
  },
  {
    name: "Masoor Dal (Red Lentil Curry)",
    image:
      "https://i.ytimg.com/vi/vCMA7BNH8z8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAmUttPeTOYkw24y3cQQr5zC7-qBA",
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["Vegan", "High-Protein", "Gluten-Free"],
    nutrition: {
      calories: 300,
      protein: 16,
      carbs: 35,
      fat: 8,
      fiber: 12,
      sugar: 3,
    },
    ingredients: [
      "1 cup red lentils",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 tsp turmeric",
      "1 tsp cumin seeds",
      "1 tsp mustard seeds",
      "2 garlic cloves, minced",
      "Salt to taste",
      "2 cups water",
      "2 tsp oil",
    ],
    instructions: [
      "Rinse lentils and boil with turmeric and water",
      "Sauté onion, garlic, tomato, and spices in oil",
      "Add sautéed mixture to cooked lentils",
      "Simmer for 5-10 minutes",
      "Serve hot with rice or roti",
    ],
  },
  {
    name: "Chole (Chickpea Curry)",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8KVzbgqijDwl7RWAQejAgnZDkeOJIo9xEfg&s",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietaryTags: ["Vegan", "High-Fiber", "Gluten-Free"],
    nutrition: {
      calories: 420,
      protein: 14,
      carbs: 40,
      fat: 18,
      fiber: 13,
      sugar: 6,
    },
    ingredients: [
      "2 cups boiled chickpeas",
      "2 tomatoes, pureed",
      "1 onion, chopped",
      "1 tsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "1/2 tsp turmeric",
      "2 tbsp oil",
      "Salt to taste",
    ],
    instructions: [
      "Heat oil, sauté onion and ginger-garlic paste",
      "Add tomato puree and spices, cook until thick",
      "Add chickpeas, mix well",
      "Simmer for 15 minutes",
      "Serve with rice or bhature",
    ],
  },
  {
    name: "Poha (Flattened Rice)",
    image:
      "https://delishably.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTc0NDI5MDY2MTc3NjE5NTkw/flattened-rice-recipe-poha.jpg",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["Vegetarian", "Low-Fat", "Gluten-Free"],
    nutrition: {
      calories: 250,
      protein: 6,
      carbs: 35,
      fat: 8,
      fiber: 4,
      sugar: 2,
    },
    ingredients: [
      "1 cup flattened rice (poha)",
      "1 onion, chopped",
      "1 green chili, chopped",
      "1/4 tsp turmeric",
      "1/2 tsp mustard seeds",
      "1 tbsp peanuts",
      "Salt to taste",
      "1 tbsp oil",
      "Fresh coriander for garnish",
      "1 tsp lemon juice",
    ],
    instructions: [
      "Rinse poha and drain excess water",
      "Heat oil, add mustard seeds, peanuts, and onions",
      "Add green chili and turmeric, sauté briefly",
      "Add poha and salt, mix well",
      "Garnish with coriander and lemon juice",
    ],
  },
  {
    name: "Vegetable Upma",
    image:
      "https://d1uz88p17r663j.cloudfront.net/original/ba32df908435796279e3d79f0d5fbdc1_Rava_Upma_-_Twist.jpg",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["Vegetarian", "Low-Fat", "Fiber-Rich"],
    nutrition: {
      calories: 280,
      protein: 7,
      carbs: 42,
      fat: 10,
      fiber: 5,
      sugar: 4,
    },
    ingredients: [
      "1 cup semolina (rava)",
      "1 onion, chopped",
      "1 carrot, diced",
      "1/4 cup green peas",
      "1 green chili, chopped",
      "1 tsp mustard seeds",
      "8-10 curry leaves",
      "2 cups water",
      "2 tsp oil",
      "Salt to taste",
    ],
    instructions: [
      "Dry roast rava and set aside",
      "Heat oil, add mustard seeds and curry leaves",
      "Sauté onions, chili, and vegetables",
      "Add water and bring to boil",
      "Add rava slowly, stir to avoid lumps",
      "Cook until soft and fluffy",
    ],
  },
  {
    name: "Moong Dal Chilla",
    image:
      "https://vegecravings.com/wp-content/uploads/2024/07/Green-Moong-Dal-Chilla-Recipe-Step-By-Step-Instructions-scaled.jpg",
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["High-Protein", "Vegan", "Gluten-Free"],
    nutrition: {
      calories: 200,
      protein: 10,
      carbs: 20,
      fat: 6,
      fiber: 6,
      sugar: 2,
    },
    ingredients: [
      "1 cup soaked yellow moong dal",
      "1 green chili",
      "1/2 inch ginger",
      "Salt to taste",
      "1/2 onion, chopped",
      "2 tbsp coriander leaves",
      "Oil for cooking",
    ],
    instructions: [
      "Grind soaked dal with chili and ginger",
      "Mix in onions, coriander, and salt",
      "Pour batter on a hot pan like a pancake",
      "Cook both sides until golden",
      "Serve with chutney",
    ],
  },
  {
    name: "Vegetable Biryani",
    image: "https://i.ytimg.com/vi/Do7ZdUodDdw/maxresdefault.jpg",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "Hard",
    cuisine: "Indian",
    dietaryTags: ["Vegetarian", "High-Carb", "Spicy"],
    nutrition: {
      calories: 520,
      protein: 10,
      carbs: 60,
      fat: 25,
      fiber: 6,
      sugar: 5,
    },
    ingredients: [
      "1 cup basmati rice",
      "1/2 cup chopped mixed vegetables",
      "1 onion, sliced",
      "2 tbsp yogurt",
      "1 tsp biryani masala",
      "1/2 tsp turmeric",
      "1/2 tsp red chili powder",
      "2 tbsp oil/ghee",
      "Salt to taste",
      "Fresh mint & coriander",
    ],
    instructions: [
      "Boil rice until 80% cooked",
      "Sauté onions and vegetables in oil",
      "Add spices and yogurt, cook 5 minutes",
      "Layer rice and masala, garnish with mint",
      "Cook on low heat for 10 minutes",
      "Serve with raita",
    ],
  },
  {
    name: "Samosa",
    image:
      "https://www.pureindianfoods.com/cdn/shop/articles/indian-samosas-recipe.webp?v=1728682315",
    prepTime: 25,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietaryTags: ["Vegetarian", "Street-Food", "Fried"],
    nutrition: {
      calories: 320,
      protein: 6,
      carbs: 30,
      fat: 18,
      fiber: 4,
      sugar: 2,
    },
    ingredients: [
      "1 cup all-purpose flour",
      "3 boiled potatoes",
      "1/2 cup peas",
      "1 tsp cumin seeds",
      "1 tsp garam masala",
      "Salt to taste",
      "Water to knead dough",
      "Oil for deep frying",
    ],
    instructions: [
      "Knead dough using flour, salt, and water",
      "Mash potatoes, mix with peas and spices",
      "Stuff into rolled dough, form triangle",
      "Deep fry until golden brown",
      "Serve with chutney",
    ],
  },
  {
    name: "Chicken Curry",
    image:
      "https://i.ytimg.com/vi/QWje6ZfXGRo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD_yZZbJhxJ3oe7hWXX62BH4RK4-w",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietaryTags: ["High-Protein", "Non-Vegetarian", "Gluten-Free"],
    nutrition: {
      calories: 480,
      protein: 35,
      carbs: 12,
      fat: 30,
      fiber: 3,
      sugar: 4,
    },
    ingredients: [
      "500g chicken pieces",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "2 tbsp oil",
      "Salt to taste",
      "Fresh coriander for garnish",
    ],
    instructions: [
      "Heat oil, sauté onions until golden",
      "Add ginger-garlic paste, cook 1 min",
      "Add tomatoes and spices, cook until oil separates",
      "Add chicken and cook until tender",
      "Garnish with coriander",
      "Serve with rice or roti",
    ],
  },
  {
    name: "Egg Bhurji (Indian Scrambled Eggs)",
    image:
      "https://swatisani.net/kitchen/wp-content/uploads/2014/12/1024px-Spicy_egg_bhurji_@_the_eggfactory.jpg",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["High-Protein", "Low-Carb", "Non-Vegetarian"],
    nutrition: {
      calories: 280,
      protein: 18,
      carbs: 4,
      fat: 22,
      fiber: 1,
      sugar: 2,
    },
    ingredients: [
      "4 eggs",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 green chili, chopped",
      "1/2 tsp turmeric",
      "Salt to taste",
      "1 tbsp oil",
      "Fresh coriander for garnish",
    ],
    instructions: [
      "Heat oil, sauté onion and green chili",
      "Add tomato and turmeric, cook till soft",
      "Beat eggs and add to pan",
      "Scramble and cook until set",
      "Garnish with coriander",
      "Serve with pav or toast",
    ],
  },
  {
    name: "Fish Fry (South Indian Style)",
    image:
      "https://www.aromaandessence.com/wp-content/uploads/2023/12/Fish-fry-2.webp",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indian",
    dietaryTags: ["High-Protein", "Keto-Friendly", "Non-Vegetarian"],
    nutrition: {
      calories: 350,
      protein: 30,
      carbs: 2,
      fat: 24,
      fiber: 1,
      sugar: 1,
    },
    ingredients: [
      "2 fish fillets",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1/2 tsp pepper",
      "1/2 tsp lemon juice",
      "Salt to taste",
      "2 tbsp oil",
    ],
    instructions: [
      "Marinate fish with spices and lemon juice",
      "Heat oil in a pan",
      "Shallow fry both sides until golden",
      "Serve hot with onion rings and lemon",
    ],
  },
  {
    name: "Butter Chicken",
    image:
      "https://realfood.tesco.com/media/images/1400x919-240222-TESCO-CEDAR-MARCH-STILLS-Butter-Chicken-Curry-TRF-0363-11-b633ee81-ae2c-4cb2-b672-771a7a0712a7-0-1400x919.jpg",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietaryTags: ["High-Protein", "Creamy", "Non-Vegetarian"],
    nutrition: {
      calories: 550,
      protein: 32,
      carbs: 14,
      fat: 40,
      fiber: 3,
      sugar: 4,
    },
    ingredients: [
      "500g boneless chicken",
      "1/2 cup yogurt",
      "1 tbsp ginger-garlic paste",
      "1 tsp red chili powder",
      "1/2 tsp turmeric",
      "1 cup tomato puree",
      "1/2 cup cream",
      "2 tbsp butter",
      "Salt to taste",
    ],
    instructions: [
      "Marinate chicken in yogurt and spices",
      "Grill or pan-fry until cooked",
      "In another pan, heat butter, add tomato puree",
      "Cook with spices, then stir in cream",
      "Add chicken, simmer 10 minutes",
      "Serve with naan or rice",
    ],
  },
];
// Seed the database with sample data
const seedDatabase = async () => {
  try {
    // Check if MongoDB is connected
    if (mongoose.connection.readyState !== 1) {
      console.log("Skipping database seeding - MongoDB not connected");
      return;
    }

    //connectToDB();
    // Clear existing recipes
    await Recipe.deleteMany({});

    // Insert mock recipes
    await Recipe.insertMany(mockRecipes);

    console.log("Database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

module.exports = seedDatabase;
